#version: '3.4'

services:
  ticketproject:
    image: ${DOCKER_REGISTRY-}ticketproject
    # cpus: "2.0"
    build:
      context: .
      dockerfile: TicketProject/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    networks:
      - my_custom_network
    sysctls:
      net.core.somaxconn: '1024'
      net.ipv4.tcp_max_syn_backlog: '2048'

  ticketproject1:
    image: ${DOCKER_REGISTRY-}ticketproject
    # cpus: "2.0"
    build:
      context: .
      dockerfile: TicketProject/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq
    networks:
      - my_custom_network
    sysctls:
        net.core.somaxconn: '1024'
        net.ipv4.tcp_max_syn_backlog: '2048'

  nginx:
    image: nginx:latest
    container_name: nginx
    # cpus: "6.0"
    ports:
      - "8070:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ticketproject
      - ticketproject1
      - vue
    networks:
      - my_custom_network

  redis:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - my_custom_network
    volumes:
      - redis_data:/data  

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_custom_network

  mssql-master:
    container_name: mssql-master
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "${MASTER_DB_PORT}:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      my_custom_network:
        ipv4_address: 172.16.0.224

  mssql-slave:
    container_name: mssql-slave
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "${SLAVE_DB_PORT}:1433"
    volumes:
      - mssql_slave_data:/var/opt/mssql
    networks:
      my_custom_network:
        ipv4_address: 172.16.0.225

  vue:
    container_name: vue
    build:
      context: ./TicketProject/FrontEnd
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./TicketProject/FrontEnd:/app:rw
    command: >
      sh -c "
      if [ ! -f 'package.json' ]; then
        npx create-vite@latest my-vue-app --template vue;
        mv my-vue-app/* .;
        rm -rf my-vue-app;
        npm install;
      elif [ ! -d 'node_modules' ]; then
        npm install;
      fi;
      npm run dev
      "
    networks:
      - my_custom_network

volumes:
  mssql-data:
  mssql_slave_data:
  redis_data:


networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
